AllCops:
  Exclude:
    - config/**/*
    - db/**/*
    - test/**/*
  RunRailsCops: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false
